In [12]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np 
import pandas as pd

In [74]:
df = pd.read_csv(r"D:\code.folder\Fullstack-AI\Text_Encoding\data\Scrapedata.csv")
df = df.drop(columns = ["Star Rating"])

In [75]:
df.head()

,Review Title,Review Description
0,Very very high cost.,"I got Mi tv 55 inch at 55K price, the wall mou..."
1,"Great product, you should buy for it if you ar...","Great product for beginners, you should try it..."
2,It is THE MIC that you need for everyday conte...,Best Microphone that I have purchased till dat...
3,Good mic but Bad magnet,Pros - It is a great product in this price ran...
4,Quality is not good,Very Bad Quality product from hollyland. Noise...

In [15]:
import nltk
from nltk.corpus import stopwords            # For stopwords list
from nltk.stem import WordNetLemmatizer      # For lemmatization

# Download the requirements
nltk.download('stopwords')
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\piyus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\piyus\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [83]:
import pandas as pd
import string

# 1. Setup
stop_words = set(stopwords.words('english'))

def clean_text(text):
    # Convert to string to handle any NaN values
    Review_text = str(text).lower() 
    
    # Remove punctuation
    Review_text = text.translate(str.maketrans('', '', string.punctuation))
    
    # Remove stopwords and rejoin into a string
    words = Review_text.split()
    cleaned_Review = [w for w in words if w not in stop_words]
    
    return " ".join(cleaned_Review)

# 3. Apply to your column
df['cleaned_Title'] = df['Review Title'].apply(clean_text)
df["Cleaned_review"] = df["Review Description"].apply(clean_text)

# 4. Convert to list (to avoid the inhomogeneous shape error)
title = df['cleaned_Title'].values.tolist()
review = df["Cleaned_review"].values.tolist()

In [84]:
df

,Review Title,Review Description,cleaned_Title,Cleaned_review
0,Very very high cost.,"I got Mi tv 55 inch at 55K price, the wall mou...",Very high cost,I got Mi tv 55 inch 55K price wall mount Price...
1,"Great product, you should buy for it if you ar...","Great product for beginners, you should try it...",Great product buy beginner,Great product beginners try I use Moto logging...
2,It is THE MIC that you need for everyday conte...,Best Microphone that I have purchased till dat...,It THE MIC need everyday content shooting Vide...,Best Microphone I purchased till date The nois...
3,Good mic but Bad magnet,Pros - It is a great product in this price ran...,Good mic Bad magnet,Pros It great product price range Audio qualit...
4,Quality is not good,Very Bad Quality product from hollyland. Noise...,Quality good,Very Bad Quality product hollyland Noise cance...
...,...,...,...,...
95,Good phone you can buy,In this price phone is very good but device is...,Good phone buy,In price phone good device heavy thick slimRead
96,Worst Phone,Battery drain issue. They claim 7000+ mah but ...,Worst Phone,Battery drain issue They claim 7000 mah barely...
97,Good phone,Good phone and camera quality is good.Read more,Good phone,Good phone camera quality goodRead
98,Redmi A5 is an excellent mobile phone.,This mobile is as per my expectations. It is e...,Redmi A5 excellent mobile phone,This mobile per expectations It excellent High...
99,Awesome Product.,Awesome Product.Read more,Awesome Product,Awesome ProductRead

In [85]:
title

['Very high cost',
 'Great product buy beginner',
 'It THE MIC need everyday content shooting Video conference',
 'Good mic Bad magnet',
 'Quality good',
 'Purchase without hesitation',
 'Value money',
 'Quality',
 'Noice cancellation works settings',
 'Nice product',
 'Good product',
 'Worth money think opinion',
 'I want replacement',
 'Premium feel charging head inside good sound',
 'Best price range',
 'Awesome microphone',
 'Best good quality sound',
 'Gereat wireless mic beginners',
 'Worth money',
 'Good product trust buy',
 'Brilliant mic great noise cancellation',
 'Best product',
 'Good But',
 'Transmittors Working',
 'Sound quality',
 'Absolutely Good',
 'Best deal 8000 segment',
 'Good entry level phone',
 'Good product affordable Prices',
 'A good solid phone pricepoint',
 'A quality phone decent specs',
 'Ok',
 'Phone Review After 3 Months Use',
 'Awesome',
 'M06 review',
 'Excellent fantastic superb',
 'Good product camera poor',
 'Stay away Samsung',
 'durable good quality',
 'Value For Money',
 'Cutdown version 5G phone',
 'Battery good',
 'LAG Under multitasking',
 'Lagging heat one min',
 'Insanely good price',
 'Very Good Phone',
 'Very nice phone need know wil perform hardcore usage',
 'Good Phone long battery usage',
 'Good phone studying longer',
 'Nice mobile',
 'Best Smartphone 20k 2026',
 'Performance battery beast',
 'Smooth phone good battery',
 'Great performance best value money phone sleek good battery',
 'Overall buy realme 15x u buy also suggest realme 15x',
 'Great device range',
 'What phone',
 'Best Smartphone 20k amoled display',
 'Amazing product',
 'Smooth gaming overall perfect price range',
 'Good',
 'Great device value money',
 'Performance',
 'IQOO phone',
 'Great productworth money',
 'Great Performance Battery But Very Poor Camera',
 'Slow mobile',
 'Value money',
 'Look wise phone good 👍😊',
 'Monsterously Amazing Galaxy',
 'GALAXY IS NOT BAD',
 'Good phone great features',
 'Amazing product',
 'Amazing product',
 'Simply Samsung phone Very 👌 Awesome',
 'Nice phone daily use',
 'good product beware exchange offers',
 'Nice phone',
 'Good product low price M17 5G',
 'Samsung Galaxy M17 5G Mobile Good mobile middle range',
 'Best phone budget',
 'Premium look build quality performance bit slow',
 'Little bit slow performence',
 'Good',
 'Samsung Galaxy M17 5G The Longevity King',
 'In price range 4g phone good',
 'An average',
 'Good',
 'Not 5g handset',
 'Fraud',
 'Simple Clean Best Budget Smartphone Solid Performance',
 'Budget option',
 'Important front Camera good back camera good',
 'Best choice regular users',
 'Value money good gaming',
 'Good phone buy',
 'Worst Phone',
 'Good phone',
 'Redmi A5 excellent mobile phone',
 'Awesome Product']

In [86]:
review

['I got Mi tv 55 inch 55K price wall mount Price 30K use buy Mi Tv budget waste moneyRead',
 'Great product beginners try I use Moto loggingThe quality product great Quality definitely nice Voice qualities perfect outdoor shoots comparability cameras great It’s easy handle need great science use The functionality product simpleRead',
 'Best Microphone I purchased till date The noise cancellation feature really good It classy look voice quality strong It compatible Android well iOS Highly recommended content creators people virtual meetings almost always Value MoneyRead',
 'Pros It great product price range Audio quality great battery life also good good option beginnersCons However 1 big shortcoming clip missing mics comes magnets The magnet quality decent small may lose easily I already lost 1 magnet first day And losing magnet becomes difficult charge handle micRead',
 'Very Bad Quality product hollyland Noise cancellation working properly Cant record good quality audioRead',
 '1st class product Im sorry happy 😁Read',
 'Value money Good voice qualityRead',
 'Highly recommend product really good quality best useRead',
 'Please read doubts respect noice cancellationWhen I first got microphone working I later found battery low charging also noticed noice cancellation working I complained even scheduled return last attempt I tried googling gemini ai I found phone picking internal microphone instead mic Later I cancelled return kept mic There 4 setting change settings external audio able work micHollyland please send instruction manual phones default especially android use internal audio even connect micIt compatible android worked well Easy use play around settings first However noice cancellation still better Its okay okay You use reels edits app use noice cancellation thereRead',
 'I specially came amazon find product write review Why By mistake I put one mics washing machine along one shirts I recalled I start another meeting clicked inside washing machine I ran stopped machine already 1015 mins wetconclusion It working even thought wet without claimed IP rating however also coincidentVery good audio quality even sitting direction coolers throwI use teams meeting windows superb works well camera wellCaution Finding core purpose calls I also tried taking normal phone calls phone however supported use apps allows select mics inputs phone PC meetings WhatsApp call breeze battery also good I usually forget shirt I observed operational continuous 45 hrs easily 1040 around 300 I switch oneIts light small I hardly notice anything stuck shirt overall good productRead',
 'Very good item used suggest go 11000 mic far bettee I purchased use dailyRead',
 'Its good product price range The sound quality voice output feom device pretty good I got product well packed damage found anywhere It good battery backup Noice reduction also good Better use app customisationRead',
 'The media could loadedHello I received microphone workingBoth transmitters turning I tried charging fully pressing power button several seconds light responseI also tried use replacement option app working allowing proceedIt seems like defective product I would like replacementPlease arrange replacement soon possible Thank youRead',
 'Charge first receive charging head included use phones charger olug receiver usbc head phone grab mic boom connected press receiver botton 6 seconds done premium feel sound clearRead',
 'noise cancelation good easy use carry value moneyRead',
 'A great product I YouTuber I satisfied purchaseRead',
 'Good product I using Iphone 17pro max it’s working good Must buy✌🏻Read',
 'ProsExcellent noise cancellation Filters background noise effectively keeping subject’s voice clear focusedHighquality audio Clear natural sound—good vlogging interviews voice recordingsStrong default gain The mic gain set high default works well outdoor recording subject isn’t close micVersatile use cases Suitable voiceovers podcasts online meetings online classes vlogs interviews etcConvenient charging case included Having case allows charge mics go especially helpful long sessions outdoor usesConsAppdependent gain control Mic gain adjusted app limits control using mic cameraBattery life Battery performance average longer shoots may require frequent chargingRange limitations The wireless range good typical use may ideal large venues obstructed environmentsMagnet mount instead clip The transmitter uses magnet mount rather traditional clip may secure well clothing typesRead',
 'The media could loadedWorth money I must say sound quality quite crisp cuts background really well super easy use download app control heck lot things magnet super strong light weight easy attach clothes doesn’t feel bulkyPS buy receivers use iPhone lighting one doesn’t come singular usbRead',
 'The media could loadedVery nice genuine product Im writing review using week I use iPhone super compatible comfortable recording videos The side may work apps But best product anyone looking mic super noise cancelation Battery life also really good I charged lasting week based usage may vary Over good product cost little higher endRead',
 'Brilliant purchase regular content creation iPhone 17 Works like charm Of special mention brilliant noise cancellation cuts ambient noise beautifully well Please make sure purchase ONLY USBC variant would save lot money since works USBC compatible devices I bought combo USBC Lightning variant cost upwards Rs7000 I purchased kit USBC variant wasnt availableRead',
 'Best bloggingI’m using industry voice cancellation working fantastic Loved itRead',
 'Mic Great But It Must Have Clips wise You Will Lose ItRead',
 'I purchased Lark AI Both transmittors working What nextRead',
 'The best product get works good voice comes crystal clearRead',
 'No issues till nowYou buy students daily use parents started useTotally worth priceRead',
 'According price best Screen large speakers loud long lasting batterylight weight usable camera Best giving grandparents want learn using smartphoneRead',
 'This good entry level phone good large 67 display Large battery android 16 one ui 8 A great phone normal use Don’t expect much camera gaming performance entry level phoneRead',
 'A Good product affordable Prices For Gifting someone special satisfactory Very Attractive Product affordable PricesRead',
 'This marketed budget phone Nonetheless quality feel midrange product It essentials well including Internet browsing WhatsApp etc The slight issue dropped wifi connection despite close proximity router Itll switch mobile data connection could consume lot data dont realise You change connection settings avoid rapid switching WiFi dataRead',
 'This phone purchased gift old person likes lot The phone looks good build quality decent price screen although FHD panel crisp colourful phone fast enough general applications like WhatsApp youtube Camera takes good pictures videos Speaker loud enough call quality via microphone also good She doesnt game sure gaming experience I cant comment battery performance I didnt check shes almost always home battery may issue Its 4G phone 5G connectivity doesnt matter us Oh receive six Android updatesAll good phone priceRead',
 'Its ok price would great 5gRead',
 'Note I using phone last 3 months basic usage It working well trust normal use ✅ Pros1 4G Support Since 4G coverage widely available phone works well everyday use2 Battery 5000 mAh battery provides excellent backup easily lasts 2 days3 Display Samsung PLS LCD display good quality smooth touch response4 Performance Helio G99 processor delivers good speed daily tasks ❌ Cons1 No 5G Support The phone support 5G bands2 Camera Camera quality average3 Limited RAM Although 4GB RAM 1GB usually free This may cause issues future Android updates multitasking4 Performance Drop Installing many apps may slow phone due limited RAM storage5 Software Updates Samsung promises 6 generations Android updates 4GB RAM 64GB storage future updates may affect performance storage 📌 ConclusionThis basic smartphone suitable calling messaging light app usage Do expect high performance advanced featuresRead',
 'fantastic product exceeded expectations Im really satisfied impressive features smooth performance reliable battery life price Highly recommended anyone tight budget 10k12k range—great value without compromisesRead',
 'The Phone nice I using last 6 monthsGood build qualityGood price rangeSupports super fast charging battery health also goodBigger screen sizeGood soundIt lags gets heated processor cannot handle much loadOverall runs smooth low moderate useRead',
 'I highly recommend costumer purchase mobile I also say really wonderful item less budget features fantasticRead',
 'The product good But looking phone takes good pictures buy The camera poor Overall performance good gaming purposes Good normal calls WhatsApp messages banking applications food applications basic applications run smoothly The battery effectiveDo expect something exceptional itRead',
 'I ordered cellphone month back horrible experience say least I tremendous trust confidence Samsung products extremely durable good quality However shattered cellphone purchase Just five days screendisplay started malfunctioning When I paid visit service centre simply updated software sent back saying work The next day cellphones display started giving problems I went service centre shock ready acknowledge hardware fault After lot struggle service centre guys changed display Its 56 days since I say surety device low hardware quality The speaker sound display infact everything feels like low quality I amazed kind experience I Samsung time I really wouldnt recommend anyone buy product Guys service centre guys behaving didnt care damn I come conclusion hardware service Samsung declined years point behaving like tin pot company Extremely disappointed sad 100 TRUE I would definitely stay away buying Samsung products future company I tremendous trust confidence I already acknowledging money drain Even Samsung would exchanged device new one I still dont think would worked really well But something done say least Read',
 'Good product low budgetRead',
 'Value Money product budget buyers safe secure using nicely blotware useless apps etcfeels good works nicely used roughly looks good premium costcons phone hangs lags memory 60 full dedicated slot biggest cons case charger head phone must budget buyers hence given 4 ratings camera decent macro wide angle availableRead',
 'I reviewing phone days usageThis compromised cutdown version normal 5G phones hence available less 10K INRThe builtin hardware test removed Dialling 0 nothingIt basic raw uncalibrated GyroscopeCamera okay Despite 128GB ROM 6GB RAM 2 GHz processor phone surprisingly slowIf signal quality around 3 bars may indoors signal falls back 4G mobile Internet practically work See speed test screenshot The test fails connect theres Internet even though mobile data 4G connection I tried every suggestion given AI even including replacing SIM new one nothing helps This device weaker antenna reception technical point viewSadly speaker sound great Its poor If next room watching TV phone rings another room might miss call speaker loudness poor even full volumeWhen take photo phone makes Click sound Theres direct setting turn theres trick available Youtube videos works mute Click soundBattery life average Charging time okay standard normal chargerOnly one good thing theres beep call recording announcement record call This might change future thoughOverall I disappointed Earlier I Redmi 7A enough space overall slow aspects I bought one overall I impressed I feel I still old experience added space nothing moreRead',
 'After 2days full use Battery 55 camera 810 display 55sound voice mic1010 5g network 1010 overall best product thank amazon sumsung indiaRead',
 'I bought 4GB RAM version unfortunately struggles multitasking If I try run two apps simultaneously noticeable lag The camera performance also quite disappointing—I’d rate 1 5 On bright side battery backup solid lasts long time Its decent basic phone power usersRead',
 'Most nonsense phone iphoneRead',
 'Insanely good priceAn rounder phone great display durability reliable performanceBattery life best class thanks Samsungs software optimizationRead',
 'Very Nice Phone I expected I using 2 phones IQOO Z10X AND Z11X And I fully Satisfied company VivoRead',
 'Very nice phone need know wil perform hardcore usageRead',
 'Good phoneGood battery lifeDecent cameraVery happy split screen new origin OS availability lower price segmentRead',
 'Bought phone brother Nice phone suitable long hour studyin usageQuite big batteryGood phone playing freefire doesnt lagLooks wise okWill share review I used fot sufficent timeRead',
 'Good product 💯Read',
 'Wonderful productsRead',
 'The experience smartphone really fantastic I bought smartphone performance battery provides things beyond expectationThe Battery last 2 days performance top notch Camera smartphone also great The display quality never felt low concerning startingOverall top notch performance top notch battery great camera system really make smartphone value priceRead',
 'I playing Freefire device The phone pretty smooth battery lasts 2 daysRead',
 'Its sleek great phoneRead',
 'First I would like talk Realme Narzo 80 Pro 5G Overall good phone 20–22k INR price range I using phone since 17 August 2025 today 28 November 2025—almost 4 months The gaming performance good The camera quality also good bright environments sunlight outdoors especially taking photos people Nature photography also decent Also sound quality also good im reading negative comments want tell whomever reading review The phone dual stereo speaker support also 300 voice boost I 8 GB RAM 128 GB storage variant I strongly suggest buying 256 GB storage variant 128 GB version large portion storage taken system—around 30–40 GB So get 60–70 GB usable space quite low modern usage Even though phone advertised 128 GB don’t actually get full 128 GBIn terms performance I face heating issues The phone stays cool normal even heavy tasks It heats slightly charging completely normal fastcharging phones The connectivity also good strong WiFi Bluetooth performance Storage transfer speeds fast well thanks UFS 31 storageI also appreciate battery capacity quite good modern phones 6000 mAh The battery lasts around 20–21 hours moderate usage YouTube Instagram Reels studying PW app However I one issue screen Although display bright easy use sunlight excellent color quality I would advise avoiding phones curved displays If curved screen breaks dropping cemented road anywhere else difficult find duplicate replacement screen marketAdditionally cannot expand memory using SD card audio jack phone On positive side 80W charging amazing—it charges phone 25 10 minutes 60 30 minutesOverall phone good I still recommend checking Realme 15x It offers almost features even better aspects doesn’t curved display The Realme 15x also comes 60W SUPERVOOC charging massive 7000 mAh battery extremely impressive lasts even longerRead',
 'Worth every penny Camera surprisingly good Phone lightweight sleek comfortable Buy p3 ultra p4 costlierRead',
 'Absolutely amazing mobile I highly recommend mobile looking mid range budget mobile I dont want call budget mobile delivering premium qualityit easily match flagship mobiles forget configuration look performance display quality giving important anything else The display great touch fantastic battery good day long I got refreshed phone long period redmi note 14 usage irritated lagging experience phone given much I wasted time previous oneThe bgmi play really amazing I dont know much fps giving I felt awesome No heat issues You pick 128gb varient save 2k intelligent storage keeper days everyone using Googleone cloud storages If reckless user go 256gb But I facing one issue phone tampered glass edges getting dirty scratches easily taking pocket curves But issue nothing front previous phone experienceNote My sincere request everyone buy redmi phones even top end phonemy previous phone redmi note 14 5g I cant say much phone irritated long periodthere plenty things say mobile I cant explain frustration hereafter 1 year use I exchanged 95k I purchased 22kRead',
 'Amazing phone fast delivery Amazon Thankyou one day delivery option Best phone amoled display screen fingerprint sensor I ordered 8256gb 20k Very lightweight amazing sound quality dual speakers Also good camera qualityRead',
 'Amazing battery backup doesnt heat nice camera sound qualityperformance also great according price Overall durable quality productRead',
 'Really amazing phone 🤩Read',
 'The product good loved value moneyRead',
 'Great value money deviceIt comes across great secondary deviceHappy lookslooks like premium deviceRead',
 'I dont face kind issue device good battery heating problem durable camera ok ok overall good device smooth good performance best budgetRead',
 'Its good phone nice colour battery lasts long etc Nice phoneRead',
 'Great phonevery handyRead',
 'The phone’s performance good battery backup also great camera quality poor If want good photo quality buying phone worth itRead',
 'Good product works slow use 2nd phoneRead',
 'Working goodDaily usage pretty goodDisplay size quality goodBattery life awesomeRecommended students family membersRead',
 'Quality good camara good according paise smooth touch heating good thanks amazon iq z10 liteRead',
 'Bought almost 5 months intense research wont regret decision Writing using device 7 daysDisplay magnificentPerformance ABattery coming good far almost 5558 hrs backup single charge Bought original Samsung 45W adapterCamera quality amazing Crisp photos better quality Use feather 120 Hz screen refresh rate Premium feel light weight Havent used games Candy Crush leisure time smooth experienceOverall monster best segment areas 4nm built Exynos 1480 great job along Xclypse GPU Its X factor 275 GHz processor sAMOLED display Bixby makes monster huge one within 25k budgetRead',
 'Battery Processor dual speaker compromiseOne UI 6 x 6 updates light weight slim premium lookdisplay quality galaxy eco systemvoice focuscamera qualityNon Chinese brand international brand value This sacrifice compromisesRead',
 'Sleek stylish design good performance Every colleagues asking model Software Samsung always great UI feels smooth Im gamer battery lasts full day I mainly got 7 os gen updates In description mentioned Android 15 For surprise I got Android 16 box great Glass back get case safety I bought niukin ripple wave soft back cover Its great l Aesthetic classy caseRead',
 'Best segment Phone The build quality camera User interface everything top notch priceThis smartphone gives full value every penny spendRead',
 'Really good phone I like Display good Camera quality smoothness sound Quality Everything good Samsung need give much charging power lower end devices 24 45 watt lessRead',
 'This phone really excellent The camera outstanding — I compared side side phones around ₹30000 range one clearly much better camera The pictures clear great quality OIS works really well It visibly better brandsThe display also excellent The colors vibrant screen extremely smooth Using phone feels enjoyable smoothThe battery performance also good One full charge easily lasts full day even heavy usageApps open fast phone feels smooth overall Games like BGMI also run smoothly I played without issuesOne small drawback single speaker However bad — speaker loud sound quality good Still stereo speakers would even betterI giving phone 4 stars single speakerOverall phone good Balanced around 25000Read',
 'Using phone since 15 days far good daily use Phone handy light weight good front n back camera Screen brightness auto adjust works wellRead',

In [27]:
tokenized_title = [s.split() for s in title]
tokenized_review = [s.split() for s in review]

In [29]:
tokenized_title

[['Very', 'high', 'cost'],
 ['Great', 'product', 'buy', 'beginner'],
 ['It',
  'THE',
  'MIC',
  'need',
  'everyday',
  'content',
  'shooting',
  'Video',
  'conference'],
 ['Good', 'mic', 'Bad', 'magnet'],
 ['Quality', 'good'],
 ['Purchase', 'without', 'hesitation'],
 ['Value', 'money'],
 ['Quality'],
 ['Noice', 'cancellation', 'works', 'settings'],
 ['Nice', 'product'],
 ['Good', 'product'],
 ['Worth', 'money', 'think', 'opinion'],
 ['I', 'want', 'replacement'],
 ['Premium', 'feel', 'charging', 'head', 'inside', 'good', 'sound'],
 ['Best', 'price', 'range'],
 ['Awesome', 'microphone'],
 ['Best', 'good', 'quality', 'sound'],
 ['Gereat', 'wireless', 'mic', 'beginners'],
 ['Worth', 'money'],
 ['Good', 'product', 'trust', 'buy'],
 ['Brilliant', 'mic', 'great', 'noise', 'cancellation'],
 ['Best', 'product'],
 ['Good', 'But'],
 ['Transmittors', 'Working'],
 ['Sound', 'quality'],
 ['Absolutely', 'Good'],
 ['Best', 'deal', '8000', 'segment'],
 ['Good', 'entry', 'level', 'phone'],
 ['Good', 'product', 'affordable', 'Prices'],
 ['A', 'good', 'solid', 'phone', 'pricepoint'],
 ['A', 'quality', 'phone', 'decent', 'specs'],
 ['Ok'],
 ['Phone', 'Review', 'After', '3', 'Months', 'Use'],
 ['Awesome'],
 ['M06', 'review'],
 ['Excellent', 'fantastic', 'superb'],
 ['Good', 'product', 'camera', 'poor'],
 ['Stay', 'away', 'Samsung'],
 ['durable', 'good', 'quality'],
 ['Value', 'For', 'Money'],
 ['Cutdown', 'version', '5G', 'phone'],
 ['Battery', 'good'],
 ['LAG', 'Under', 'multitasking'],
 ['Lagging', 'heat', 'one', 'min'],
 ['Insanely', 'good', 'price'],
 ['Very', 'Good', 'Phone'],
 ['Very',
  'nice',
  'phone',
  'need',
  'know',
  'wil',
  'perform',
  'hardcore',
  'usage'],
 ['Good', 'Phone', 'long', 'battery', 'usage'],
 ['Good', 'phone', 'studying', 'longer'],
 ['Nice', 'mobile'],
 ['Best', 'Smartphone', '20k', '2026'],
 ['Performance', 'battery', 'beast'],
 ['Smooth', 'phone', 'good', 'battery'],
 ['Great',
  'performance',
  'best',
  'value',
  'money',
  'phone',
  'sleek',
  'good',
  'battery'],
 ['Overall',
  'buy',
  'realme',
  '15x',
  'u',
  'buy',
  'also',
  'suggest',
  'realme',
  '15x'],
 ['Great', 'device', 'range'],
 ['What', 'phone'],
 ['Best', 'Smartphone', '20k', 'amoled', 'display'],
 ['Amazing', 'product'],
 ['Smooth', 'gaming', 'overall', 'perfect', 'price', 'range'],
 ['Good'],
 ['Great', 'device', 'value', 'money'],
 ['Performance'],
 ['IQOO', 'phone'],
 ['Great', 'productworth', 'money'],
 ['Great', 'Performance', 'Battery', 'But', 'Very', 'Poor', 'Camera'],
 ['Slow', 'mobile'],
 ['Value', 'money'],
 ['Look', 'wise', 'phone', 'good', '👍😊'],
 ['Monsterously', 'Amazing', 'Galaxy'],
 ['GALAXY', 'IS', 'NOT', 'BAD'],
 ['Good', 'phone', 'great', 'features'],
 ['Amazing', 'product'],
 ['Amazing', 'product'],
 ['Simply', 'Samsung', 'phone', 'Very', '👌', 'Awesome'],
 ['Nice', 'phone', 'daily', 'use'],
 ['good', 'product', 'beware', 'exchange', 'offers'],
 ['Nice', 'phone'],
 ['Good', 'product', 'low', 'price', 'M17', '5G'],
 ['Samsung',
  'Galaxy',
  'M17',
  '5G',
  'Mobile',
  'Good',
  'mobile',
  'middle',
  'range'],
 ['Best', 'phone', 'budget'],
 ['Premium', 'look', 'build', 'quality', 'performance', 'bit', 'slow'],
 ['Little', 'bit', 'slow', 'performence'],
 ['Good'],
 ['Samsung', 'Galaxy', 'M17', '5G', 'The', 'Longevity', 'King'],
 ['In', 'price', 'range', '4g', 'phone', 'good'],
 ['An', 'average'],
 ['Good'],
 ['Not', '5g', 'handset'],
 ['Fraud'],
 ['Simple', 'Clean', 'Best', 'Budget', 'Smartphone', 'Solid', 'Performance'],
 ['Budget', 'option'],
 ['Important', 'front', 'Camera', 'good', 'back', 'camera', 'good'],
 ['Best', 'choice', 'regular', 'users'],
 ['Value', 'money', 'good', 'gaming'],
 ['Good', 'phone', 'buy'],
 ['Worst', 'Phone'],
 ['Good', 'phone'],
 ['Redmi', 'A5', 'excellent', 'mobile', 'phone'],
 ['Awesome', 'Product']]

In [31]:
tokenized_review

[['I',
  'got',
  'Mi',
  'tv',
  '55',
  'inch',
  '55K',
  'price',
  'wall',
  'mount',
  'Price',
  '30K',
  'use',
  'buy',
  'Mi',
  'Tv',
  'budget',
  'waste',
  'moneyRead'],
 ['Great',
  'product',
  'beginners',
  'try',
  'I',
  'use',
  'Moto',
  'loggingThe',
  'quality',
  'product',
  'great',
  'Quality',
  'definitely',
  'nice',
  'Voice',
  'qualities',
  'perfect',
  'outdoor',
  'shoots',
  'comparability',
  'cameras',
  'great',
  'It’s',
  'easy',
  'handle',
  'need',
  'great',
  'science',
  'use',
  'The',
  'functionality',
  'product',
  'simpleRead'],
 ['Best',
  'Microphone',
  'I',
  'purchased',
  'till',
  'date',
  'The',
  'noise',
  'cancellation',
  'feature',
  'really',
  'good',
  'It',
  'classy',
  'look',
  'voice',
  'quality',
  'strong',
  'It',
  'compatible',
  'Android',
  'well',
  'iOS',
  'Highly',
  'recommended',
  'content',
  'creators',
  'people',
  'virtual',
  'meetings',
  'almost',
  'always',
  'Value',
  'MoneyRead'],
 ['Pros',
  'It',
  'great',
  'product',
  'price',
  'range',
  'Audio',
  'quality',
  'great',
  'battery',
  'life',
  'also',
  'good',
  'good',
  'option',
  'beginnersCons',
  'However',
  '1',
  'big',
  'shortcoming',
  'clip',
  'missing',
  'mics',
  'comes',
  'magnets',
  'The',
  'magnet',
  'quality',
  'decent',
  'small',
  'may',
  'lose',
  'easily',
  'I',
  'already',
  'lost',
  '1',
  'magnet',
  'first',
  'day',
  'And',
  'losing',
  'magnet',
  'becomes',
  'difficult',
  'charge',
  'handle',
  'micRead'],
 ['Very',
  'Bad',
  'Quality',
  'product',
  'hollyland',
  'Noise',
  'cancellation',
  'working',
  'properly',
  'Cant',
  'record',
  'good',
  'quality',
  'audioRead'],
 ['1st', 'class', 'product', 'Im', 'sorry', 'happy', '😁Read'],
 ['Value', 'money', 'Good', 'voice', 'qualityRead'],
 ['Highly',
  'recommend',
  'product',
  'really',
  'good',
  'quality',
  'best',
  'useRead'],
 ['Please',
  'read',
  'doubts',
  'respect',
  'noice',
  'cancellationWhen',
  'I',
  'first',
  'got',
  'microphone',
  'working',
  'I',
  'later',
  'found',
  'battery',
  'low',
  'charging',
  'also',
  'noticed',
  'noice',
  'cancellation',
  'working',
  'I',
  'complained',
  'even',
  'scheduled',
  'return',
  'last',
  'attempt',
  'I',
  'tried',
  'googling',
  'gemini',
  'ai',
  'I',
  'found',
  'phone',
  'picking',
  'internal',
  'microphone',
  'instead',
  'mic',
  'Later',
  'I',
  'cancelled',
  'return',
  'kept',
  'mic',
  'There',
  '4',
  'setting',
  'change',
  'settings',
  'external',
  'audio',
  'able',
  'work',
  'micHollyland',
  'please',
  'send',
  'instruction',
  'manual',
  'phones',
  'default',
  'especially',
  'android',
  'use',
  'internal',
  'audio',
  'even',
  'connect',
  'micIt',
  'compatible',
  'android',
  'worked',
  'well',
  'Easy',
  'use',
  'play',
  'around',
  'settings',
  'first',
  'However',
  'noice',
  'cancellation',
  'still',
  'better',
  'Its',
  'okay',
  'okay',
  'You',
  'use',
  'reels',
  'edits',
  'app',
  'use',
  'noice',
  'cancellation',
  'thereRead'],
 ['I',
  'specially',
  'came',
  'amazon',
  'find',
  'product',
  'write',
  'review',
  'Why',
  'By',
  'mistake',
  'I',
  'put',
  'one',
  'mics',
  'washing',
  'machine',
  'along',
  'one',
  'shirts',
  'I',
  'recalled',
  'I',
  'start',
  'another',
  'meeting',
  'clicked',
  'inside',
  'washing',
  'machine',
  'I',
  'ran',
  'stopped',
  'machine',
  'already',
  '1015',
  'mins',
  'wetconclusion',
  'It',
  'working',
  'even',
  'thought',
  'wet',
  'without',
  'claimed',
  'IP',
  'rating',
  'however',
  'also',
  'coincidentVery',
  'good',
  'audio',
  'quality',
  'even',
  'sitting',
  'direction',
  'coolers',
  'throwI',
  'use',
  'teams',
  'meeting',
  'windows',
  'superb',
  'works',
  'well',
  'camera',
  'wellCaution',
  'Finding',
  'core',
  'purpose',
  'calls',
  'I',
  'also',
  'tried',
  'taking',
  'normal',
  'phone',
  'calls',
  'phone',
  'however',
  'supported',
  'use',
  'apps',
  'allows',
  'select',
  'mics',
  'inputs',
  'phone',
  'PC',
  'meetings',
  'WhatsApp',
  'call',
  'breeze',
  'battery',
  'also',
  'good',
  'I',
  'usually',
  'forget',
  'shirt',
  'I',
  'observed',
  'operational',
  'continuous',
  '45',
  'hrs',
  'easily',
  '1040',
  'around',
  '300',
  'I',
  'switch',
  'oneIts',
  'light',
  'small',
  'I',
  'hardly',
  'notice',
  'anything',
  'stuck',
  'shirt',
  'overall',
  'good',
  'productRead'],
 ['Very',
  'good',
  'item',
  'used',
  'suggest',
  'go',
  '11000',
  'mic',
  'far',
  'bettee',
  'I',
  'purchased',
  'use',
  'dailyRead'],
 ['Its',
  'good',
  'product',
  'price',
  'range',
  'The',
  'sound',
  'quality',
  'voice',
  'output',
  'feom',
  'device',
  'pretty',
  'good',
  'I',
  'got',
  'product',
  'well',
  'packed',
  'damage',
  'found',
  'anywhere',
  'It',
  'good',
  'battery',
  'backup',
  'Noice',
  'reduction',
  'also',
  'good',
  'Better',
  'use',
  'app',
  'customisationRead'],
 ['The',
  'media',
  'could',
  'loadedHello',
  'I',
  'received',
  'microphone',
  'workingBoth',
  'transmitters',
  'turning',
  'I',
  'tried',
  'charging',
  'fully',
  'pressing',
  'power',
  'button',
  'several',
  'seconds',
  'light',
  'responseI',
  'also',
  'tried',
  'use',
  'replacement',
  'option',
  'app',
  'working',
  'allowing',
  'proceedIt',
  'seems',
  'like',
  'defective',
  'product',
  'I',
  'would',
  'like',
  'replacementPlease',
  'arrange',
  'replacement',
  'soon',
  'possible',
  'Thank',
  'youRead'],
 ['Charge',
  'first',
  'receive',
  'charging',
  'head',
  'included',
  'use',
  'phones',
  'charger',
  'olug',
  'receiver',
  'usbc',
  'head',
  'phone',
  'grab',
  'mic',
  'boom',
  'connected',
  'press',
  'receiver',
  'botton',
  '6',
  'seconds',
  'done',
  'premium',
  'feel',
  'sound',
  'clearRead'],
 ['noise',
  'cancelation',
  'good',
  'easy',
  'use',
  'carry',
  'value',
  'moneyRead'],
 ['A', 'great', 'product', 'I', 'YouTuber', 'I', 'satisfied', 'purchaseRead'],
 ['Good',
  'product',
  'I',
  'using',
  'Iphone',
  '17pro',
  'max',
  'it’s',
  'working',
  'good',
  'Must',
  'buy✌🏻Read'],
 ['ProsExcellent',
  'noise',
  'cancellation',
  'Filters',
  'background',
  'noise',
  'effectively',
  'keeping',
  'subject’s',
  'voice',
  'clear',
  'focusedHighquality',
  'audio',
  'Clear',
  'natural',
  'sound—good',
  'vlogging',
  'interviews',
  'voice',
  'recordingsStrong',
  'default',
  'gain',
  'The',
  'mic',
  'gain',
  'set',
  'high',
  'default',
  'works',
  'well',
  'outdoor',
  'recording',
  'subject',
  'isn’t',
  'close',
  'micVersatile',
  'use',
  'cases',
  'Suitable',
  'voiceovers',
  'podcasts',
  'online',
  'meetings',
  'online',
  'classes',
  'vlogs',
  'interviews',
  'etcConvenient',
  'charging',
  'case',
  'included',
  'Having',
  'case',
  'allows',
  'charge',
  'mics',
  'go',
  'especially',
  'helpful',
  'long',
  'sessions',
  'outdoor',
  'usesConsAppdependent',
  'gain',
  'control',
  'Mic',
  'gain',
  'adjusted',
  'app',
  'limits',
  'control',
  'using',
  'mic',
  'cameraBattery',
  'life',
  'Battery',
  'performance',
  'average',
  'longer',
  'shoots',
  'may',
  'require',
  'frequent',
  'chargingRange',
  'limitations',
  'The',
  'wireless',
  'range',
  'good',
  'typical',
  'use',
  'may',
  'ideal',
  'large',
  'venues',
  'obstructed',
  'environmentsMagnet',
  'mount',
  'instead',
  'clip',
  'The',
  'transmitter',
  'uses',
  'magnet',
  'mount',
  'rather',
  'traditional',
  'clip',
  'may',
  'secure',
  'well',
  'clothing',
  'typesRead'],
 ['The',
  'media',
  'could',
  'loadedWorth',
  'money',
  'I',
  'must',
  'say',
  'sound',
  'quality',
  'quite',
  'crisp',
  'cuts',
  'background',
  'really',
  'well',
  'super',
  'easy',
  'use',
  'download',
  'app',
  'control',
  'heck',
  'lot',
  'things',
  'magnet',
  'super',
  'strong',
  'light',
  'weight',
  'easy',
  'attach',
  'clothes',
  'doesn’t',
  'feel',
  'bulkyPS',
  'buy',
  'receivers',
  'use',
  'iPhone',
  'lighting',
  'one',
  'doesn’t',
  'come',
  'singular',
  'usbRead'],
 ['The',
  'media',
  'could',
  'loadedVery',
  'nice',
  'genuine',
  'product',
  'Im',
  'writing',
  'review',
  'using',
  'week',
  'I',
  'use',
  'iPhone',
  'super',
  'compatible',
  'comfortable',
  'recording',
  'videos',
  'The',
  'side',
  'may',
  'work',
  'apps',
  'But',
  'best',
  'product',
  'anyone',
  'looking',
  'mic',
  'super',
  'noise',
  'cancelation',
  'Battery',
  'life',
  'also',
  'really',
  'good',
  'I',
  'charged',
  'lasting',
  'week',
  'based',
  'usage',
  'may',
  'vary',
  'Over',
  'good',
  'product',
  'cost',
  'little',
  'higher',
  'endRead'],
 ['Brilliant',
  'purchase',
  'regular',
  'content',
  'creation',
  'iPhone',
  '17',
  'Works',
  'like',
  'charm',
  'Of',
  'special',
  'mention',
  'brilliant',
  'noise',
  'cancellation',
  'cuts',
  'ambient',
  'noise',
  'beautifully',
  'well',
  'Please',
  'make',
  'sure',
  'purchase',
  'ONLY',
  'USBC',
  'variant',
  'would',
  'save',
  'lot',
  'money',
  'since',
  'works',
  'USBC',
  'compatible',
  'devices',
  'I',
  'bought',
  'combo',
  'USBC',
  'Lightning',
  'variant',
  'cost',
  'upwards',
  'Rs7000',
  'I',
  'purchased',
  'kit',
  'USBC',
  'variant',
  'wasnt',
  'availableRead'],
 ['Best',
  'bloggingI’m',
  'using',
  'industry',
  'voice',
  'cancellation',
  'working',
  'fantastic',
  'Loved',
  'itRead'],
 ['Mic',
  'Great',
  'But',
  'It',
  'Must',
  'Have',
  'Clips',
  'wise',
  'You',
  'Will',
  'Lose',
  'ItRead'],
 ['I',
  'purchased',
  'Lark',
  'AI',
  'Both',
  'transmittors',
  'working',
  'What',
  'nextRead'],
 ['The',
  'best',
  'product',
  'get',
  'works',
  'good',
  'voice',
  'comes',
  'crystal',
  'clearRead'],
 ['No',
  'issues',
  'till',
  'nowYou',
  'buy',
  'students',
  'daily',
  'use',
  'parents',
  'started',
  'useTotally',
  'worth',
  'priceRead'],
 ['According',
  'price',
  'best',
  'Screen',
  'large',
  'speakers',
  'loud',
  'long',
  'lasting',
  'batterylight',
  'weight',
  'usable',
  'camera',
  'Best',
  'giving',
  'grandparents',
  'want',
  'learn',
  'using',
  'smartphoneRead'],
 ['This',
  'good',
  'entry',
  'level',
  'phone',
  'good',
  'large',
  '67',
  'display',
  'Large',
  'battery',
  'android',
  '16',
  'one',
  'ui',
  '8',
  'A',
  'great',
  'phone',
  'normal',
  'use',
  'Don’t',
  'expect',
  'much',
  'camera',
  'gaming',
  'performance',
  'entry',
  'level',
  'phoneRead'],
 ['A',
  'Good',
  'product',
  'affordable',
  'Prices',
  'For',
  'Gifting',
  'someone',
  'special',
  'satisfactory',
  'Very',
  'Attractive',
  'Product',
  'affordable',
  'PricesRead'],
 ['This',
  'marketed',
  'budget',
  'phone',
  'Nonetheless',
  'quality',
  'feel',
  'midrange',
  'product',
  'It',
  'essentials',
  'well',
  'including',
  'Internet',
  'browsing',
  'WhatsApp',
  'etc',
  'The',
  'slight',
  'issue',
  'dropped',
  'wifi',
  'connection',
  'despite',
  'close',
  'proximity',
  'router',
  'Itll',
  'switch',
  'mobile',
  'data',
  'connection',
  'could',
  'consume',
  'lot',
  'data',
  'dont',
  'realise',
  'You',
  'change',
  'connection',
  'settings',
  'avoid',
  'rapid',
  'switching',
  'WiFi',
  'dataRead'],
 ['This',
  'phone',
  'purchased',
  'gift',
  'old',
  'person',
  'likes',
  'lot',
  'The',
  'phone',
  'looks',
  'good',
  'build',
  'quality',
  'decent',
  'price',
  'screen',
  'although',
  'FHD',
  'panel',
  'crisp',
  'colourful',
  'phone',
  'fast',
  'enough',
  'general',
  'applications',
  'like',
  'WhatsApp',
  'youtube',
  'Camera',
  'takes',
  'good',
  'pictures',
  'videos',
  'Speaker',
  'loud',
  'enough',
  'call',
  'quality',
  'via',
  'microphone',
  'also',
  'good',
  'She',
  'doesnt',
  'game',
  'sure',
  'gaming',
  'experience',
  'I',
  'cant',
  'comment',
  'battery',
  'performance',
  'I',
  'didnt',
  'check',
  'shes',
  'almost',
  'always',
  'home',
  'battery',
  'may',
  'issue',
  'Its',
  '4G',
  'phone',
  '5G',
  'connectivity',
  'doesnt',
  'matter',
  'us',
  'Oh',
  'receive',
  'six',
  'Android',
  'updatesAll',
  'good',
  'phone',
  'priceRead'],
 ['Its', 'ok', 'price', 'would', 'great', '5gRead'],
 ['Note',
  'I',
  'using',
  'phone',
  'last',
  '3',
  'months',
  'basic',
  'usage',
  'It',
  'working',
  'well',
  'trust',
  'normal',
  'use',
  '✅',
  'Pros1',
  '4G',
  'Support',
  'Since',
  '4G',
  'coverage',
  'widely',
  'available',
  'phone',
  'works',
  'well',
  'everyday',
  'use2',
  'Battery',
  '5000',
  'mAh',
  'battery',
  'provides',
  'excellent',
  'backup',
  'easily',
  'lasts',
  '2',
  'days3',
  'Display',
  'Samsung',
  'PLS',
  'LCD',
  'display',
  'good',
  'quality',
  'smooth',
  'touch',
  'response4',
  'Performance',
  'Helio',
  'G99',
  'processor',
  'delivers',
  'good',
  'speed',
  'daily',
  'tasks',
  '❌',
  'Cons1',
  'No',
  '5G',
  'Support',
  'The',
  'phone',
  'support',
  '5G',
  'bands2',
  'Camera',
  'Camera',
  'quality',
  'average3',
  'Limited',
  'RAM',
  'Although',
  '4GB',
  'RAM',
  '1GB',
  'usually',
  'free',
  'This',
  'may',
  'cause',
  'issues',
  'future',
  'Android',
  'updates',
  'multitasking4',
  'Performance',
  'Drop',
  'Installing',
  'many',
  'apps',
  'may',
  'slow',
  'phone',
  'due',
  'limited',
  'RAM',
  'storage5',
  'Software',
  'Updates',
  'Samsung',
  'promises',
  '6',
  'generations',
  'Android',
  'updates',
  '4GB',
  'RAM',
  '64GB',
  'storage',
  'future',
  'updates',
  'may',
  'affect',
  'performance',
  'storage',
  '📌',
  'ConclusionThis',
  'basic',
  'smartphone',
  'suitable',
  'calling',
  'messaging',
  'light',
  'app',
  'usage',
  'Do',
  'expect',
  'high',
  'performance',
  'advanced',
  'featuresRead'],
 ['fantastic',
  'product',
  'exceeded',
  'expectations',
  'Im',
  'really',
  'satisfied',
  'impressive',
  'features',
  'smooth',
  'performance',
  'reliable',
  'battery',
  'life',
  'price',
  'Highly',
  'recommended',
  'anyone',
  'tight',
  'budget',
  '10k12k',
  'range—great',
  'value',
  'without',
  'compromisesRead'],
 ['The',
  'Phone',
  'nice',
  'I',
  'using',
  'last',
  '6',
  'monthsGood',
  'build',
  'qualityGood',
  'price',
  'rangeSupports',
  'super',
  'fast',
  'charging',
  'battery',
  'health',
  'also',
  'goodBigger',
  'screen',
  'sizeGood',
  'soundIt',
  'lags',
  'gets',
  'heated',
  'processor',
  'cannot',
  'handle',
  'much',
  'loadOverall',
  'runs',
  'smooth',
  'low',
  'moderate',
  'useRead'],
 ['I',
  'highly',
  'recommend',
  'costumer',
  'purchase',
  'mobile',
  'I',
  'also',
  'say',
  'really',
  'wonderful',
  'item',
  'less',
  'budget',
  'features',
  'fantasticRead'],
 ['The',
  'product',
  'good',
  'But',
  'looking',
  'phone',
  'takes',
  'good',
  'pictures',
  'buy',
  'The',
  'camera',
  'poor',
  'Overall',
  'performance',
  'good',
  'gaming',
  'purposes',
  'Good',
  'normal',
  'calls',
  'WhatsApp',
  'messages',
  'banking',
  'applications',
  'food',
  'applications',
  'basic',
  'applications',
  'run',
  'smoothly',
  'The',
  'battery',
  'effectiveDo',
  'expect',
  'something',
  'exceptional',
  'itRead'],
 ['I',
  'ordered',
  'cellphone',
  'month',
  'back',
  'horrible',
  'experience',
  'say',
  'least',
  'I',
  'tremendous',
  'trust',
  'confidence',
  'Samsung',
  'products',
  'extremely',
  'durable',
  'good',
  'quality',
  'However',
  'shattered',
  'cellphone',
  'purchase',
  'Just',
  'five',
  'days',
  'screendisplay',
  'started',
  'malfunctioning',
  'When',
  'I',
  'paid',
  'visit',
  'service',
  'centre',
  'simply',
  'updated',
  'software',
  'sent',
  'back',
  'saying',
  'work',
  'The',
  'next',
  'day',
  'cellphones',
  'display',
  'started',
  'giving',
  'problems',
  'I',
  'went',
  'service',
  'centre',
  'shock',
  'ready',
  'acknowledge',
  'hardware',
  'fault',
  'After',
  'lot',
  'struggle',
  'service',
  'centre',
  'guys',
  'changed',
  'display',
  'Its',
  '56',
  'days',
  'since',
  'I',
  'say',
  'surety',
  'device',
  'low',
  'hardware',
  'quality',
  'The',
  'speaker',
  'sound',
  'display',
  'infact',
  'everything',
  'feels',
  'like',
  'low',
  'quality',
  'I',
  'amazed',
  'kind',
  'experience',
  'I',
  'Samsung',
  'time',
  'I',
  'really',
  'wouldnt',
  'recommend',
  'anyone',
  'buy',
  'product',
  'Guys',
  'service',
  'centre',
  'guys',
  'behaving',
  'didnt',
  'care',
  'damn',
  'I',
  'come',
  'conclusion',
  'hardware',
  'service',
  'Samsung',
  'declined',
  'years',
  'point',
  'behaving',
  'like',
  'tin',
  'pot',
  'company',
  'Extremely',
  'disappointed',
  'sad',
  '100',
  'TRUE',
  'I',
  'would',
  'definitely',
  'stay',
  'away',
  'buying',
  'Samsung',
  'products',
  'future',
  'company',
  'I',
  'tremendous',
  'trust',
  'confidence',
  'I',
  'already',
  'acknowledging',
  'money',
  'drain',
  'Even',
  'Samsung',
  'would',
  'exchanged',
  'device',
  'new',
  'one',
  'I',
  'still',
  'dont',
  'think',
  'would',
  'worked',
  'really',
  'well',
  'But',
  'something',
  'done',
  'say',
  'least',
  'Read'],
 ['Good', 'product', 'low', 'budgetRead'],
 ['Value',
  'Money',
  'product',
  'budget',
  'buyers',
  'safe',
  'secure',
  'using',
  'nicely',
  'blotware',
  'useless',
  'apps',
  'etcfeels',
  'good',
  'works',
  'nicely',
  'used',
  'roughly',
  'looks',
  'good',
  'premium',
  'costcons',
  'phone',
  'hangs',
  'lags',
  'memory',
  '60',
  'full',
  'dedicated',
  'slot',
  'biggest',
  'cons',
  'case',
  'charger',
  'head',
  'phone',
  'must',
  'budget',
  'buyers',
  'hence',
  'given',
  '4',
  'ratings',
  'camera',
  'decent',
  'macro',
  'wide',
  'angle',
  'availableRead'],
 ['I',
  'reviewing',
  'phone',
  'days',
  'usageThis',
  'compromised',
  'cutdown',
  'version',
  'normal',
  '5G',
  'phones',
  'hence',
  'available',
  'less',
  '10K',
  'INRThe',
  'builtin',
  'hardware',
  'test',
  'removed',
  'Dialling',
  '0',
  'nothingIt',
  'basic',
  'raw',
  'uncalibrated',
  'GyroscopeCamera',
  'okay',
  'Despite',
  '128GB',
  'ROM',
  '6GB',
  'RAM',
  '2',
  'GHz',
  'processor',
  'phone',
  'surprisingly',
  'slowIf',
  'signal',
  'quality',
  'around',
  '3',
  'bars',
  'may',
  'indoors',
  'signal',
  'falls',
  'back',
  '4G',
  'mobile',
  'Internet',
  'practically',
  'work',
  'See',
  'speed',
  'test',
  'screenshot',
  'The',
  'test',
  'fails',
  'connect',
  'theres',
  'Internet',
  'even',
  'though',
  'mobile',
  'data',
  '4G',
  'connection',
  'I',
  'tried',
  'every',
  'suggestion',
  'given',
  'AI',
  'even',
  'including',
  'replacing',
  'SIM',
  'new',
  'one',
  'nothing',
  'helps',
  'This',
  'device',
  'weaker',
  'antenna',
  'reception',
  'technical',
  'point',
  'viewSadly',
  'speaker',
  'sound',
  'great',
  'Its',
  'poor',
  'If',
  'next',
  'room',
  'watching',
  'TV',
  'phone',
  'rings',
  'another',
  'room',
  'might',
  'miss',
  'call',
  'speaker',
  'loudness',
  'poor',
  'even',
  'full',
  'volumeWhen',
  'take',
  'photo',
  'phone',
  'makes',
  'Click',
  'sound',
  'Theres',
  'direct',
  'setting',
  'turn',
  'theres',
  'trick',
  'available',
  'Youtube',
  'videos',
  'works',
  'mute',
  'Click',
  'soundBattery',
  'life',
  'average',
  'Charging',
  'time',
  'okay',
  'standard',
  'normal',
  'chargerOnly',
  'one',
  'good',
  'thing',
  'theres',
  'beep',
  'call',
  'recording',
  'announcement',
  'record',
  'call',
  'This',
  'might',
  'change',
  'future',
  'thoughOverall',
  'I',
  'disappointed',
  'Earlier',
  'I',
  'Redmi',
  '7A',
  'enough',
  'space',
  'overall',
  'slow',
  'aspects',
  'I',
  'bought',
  'one',
  'overall',
  'I',

In [37]:
from collections import Counter

In [43]:
Title_words = Counter([Title_words for sublist in tokenized_title for Title_words in sublist])
Reviews_word = Counter([Title_review for sublist in tokenized_review for Title_review in sublist])

In [41]:
Title_words

Counter({'phone': 20,
         'Good': 19,
         'good': 15,
         'product': 12,
         'Best': 9,
         'money': 8,
         'Great': 6,
         'Very': 5,
         'buy': 5,
         'price': 5,
         'range': 5,
         'quality': 5,
         'Value': 4,
         'Nice': 4,
         'Awesome': 4,
         'Phone': 4,
         'Samsung': 4,
         '5G': 4,
         'battery': 4,
         'mobile': 4,
         'Performance': 4,
         'Amazing': 4,
         'mic': 3,
         'Smartphone': 3,
         'Galaxy': 3,
         'M17': 3,
         'need': 2,
         'Quality': 2,
         'cancellation': 2,
         'Worth': 2,
         'Premium': 2,
         'sound': 2,
         'great': 2,
         'But': 2,
         'A': 2,
         'camera': 2,
         'Battery': 2,
         'usage': 2,
         '20k': 2,
         'Smooth': 2,
         'performance': 2,
         'value': 2,
         'realme': 2,
         '15x': 2,
         'device': 2,
         'gaming': 2,
         'Camera': 2,
         'bit': 2,
         'slow': 2,
         'Budget': 2,
         'high': 1,
         'cost': 1,
         'beginner': 1,
         'It': 1,
         'THE': 1,
         'MIC': 1,
         'everyday': 1,
         'content': 1,
         'shooting': 1,
         'Video': 1,
         'conference': 1,
         'Bad': 1,
         'magnet': 1,
         'Purchase': 1,
         'without': 1,
         'hesitation': 1,
         'Noice': 1,
         'works': 1,
         'settings': 1,
         'think': 1,
         'opinion': 1,
         'I': 1,
         'want': 1,
         'replacement': 1,
         'feel': 1,
         'charging': 1,
         'head': 1,
         'inside': 1,
         'microphone': 1,
         'Gereat': 1,
         'wireless': 1,
         'beginners': 1,
         'trust': 1,
         'Brilliant': 1,
         'noise': 1,
         'Transmittors': 1,
         'Working': 1,
         'Sound': 1,
         'Absolutely': 1,
         'deal': 1,
         '8000': 1,
         'segment': 1,
         'entry': 1,
         'level': 1,
         'affordable': 1,
         'Prices': 1,
         'solid': 1,
         'pricepoint': 1,
         'decent': 1,
         'specs': 1,
         'Ok': 1,
         'Review': 1,
         'After': 1,
         '3': 1,
         'Months': 1,
         'Use': 1,
         'M06': 1,
         'review': 1,
         'Excellent': 1,
         'fantastic': 1,
         'superb': 1,
         'poor': 1,
         'Stay': 1,
         'away': 1,
         'durable': 1,
         'For': 1,
         'Money': 1,
         'Cutdown': 1,
         'version': 1,
         'LAG': 1,
         'Under': 1,
         'multitasking': 1,
         'Lagging': 1,
         'heat': 1,
         'one': 1,
         'min': 1,
         'Insanely': 1,
         'nice': 1,
         'know': 1,
         'wil': 1,
         'perform': 1,
         'hardcore': 1,
         'long': 1,
         'studying': 1,
         'longer': 1,
         '2026': 1,
         'beast': 1,
         'best': 1,
         'sleek': 1,
         'Overall': 1,
         'u': 1,
         'also': 1,
         'suggest': 1,
         'What': 1,
         'amoled': 1,
         'display': 1,
         'overall': 1,
         'perfect': 1,
         'IQOO': 1,
         'productworth': 1,
         'Poor': 1,
         'Slow': 1,
         'Look': 1,
         'wise': 1,
         '👍😊': 1,
         'Monsterously': 1,
         'GALAXY': 1,
         'IS': 1,
         'NOT': 1,
         'BAD': 1,
         'features': 1,
         'Simply': 1,
         '👌': 1,
         'daily': 1,
         'use': 1,
         'beware': 1,
         'exchange': 1,
         'offers': 1,
         'low': 1,
         'Mobile': 1,
         'middle': 1,
         'budget': 1,
         'look': 1,
         'build': 1,
         'Little': 1,
         'performence': 1,
         'The': 1,
         'Longevity': 1,
         'King': 1,
         'In': 1,
         '4g': 1,
         'An': 1,
         'average': 1,
         'Not': 1,
         '5g': 1,
         'handset': 1,
         'Fraud': 1,
         'Simple': 1,
         'Clean': 1,
         'Solid': 1,
         'option': 1,
         'Important': 1,
         'front': 1,
         'back': 1,
         'choice': 1,
         'regular': 1,
         'users': 1,
         'Worst': 1,
         'Redmi': 1,
         'A5': 1,
         'excellent': 1,
         'Product': 1})

In [46]:
Reviews_word

(Counter({'I': 108,
          'good': 80,
          'phone': 79,
          'The': 44,
          'quality': 42,
          'product': 36,
          'battery': 31,
          'also': 31,
          'use': 30,
          'camera': 25,
          'great': 24,
          'performance': 22,
          'hai': 18,
          'display': 17,
          'price': 16,
          'really': 15,
          'It': 15,
          'one': 15,
          'well': 14,
          'even': 14,
          'Samsung': 14,
          'using': 13,
          'smooth': 13,
          'aur': 13,
          'buy': 12,
          'budget': 12,
          'may': 12,
          'Good': 12,
          'charging': 12,
          'Its': 12,
          'This': 12,
          'sound': 11,
          'device': 11,
          'like': 11,
          'would': 11,
          'mobile': 11,
          'screen': 11,
          'money': 10,
          'best': 10,
          'phones': 10,
          'works': 10,
          'Camera': 10,
          'experience': 10,
          'voice': 9,
          'working': 9,
          'low': 9,
          'normal': 9,
          'value': 9,
          'long': 9,
          'say': 9,
          '5G': 9,
          'lasts': 9,
          'RAM': 9,
          'smartphone': 9,
          'features': 9,
          'back': 9,
          'full': 9,
          'cancellation': 8,
          'range': 8,
          'life': 8,
          'decent': 8,
          'easily': 8,
          'Very': 8,
          'overall': 8,
          'backup': 8,
          'Battery': 8,
          'usage': 8,
          'bought': 8,
          'issue': 8,
          'excellent': 8,
          'days': 8,
          'time': 8,
          'Realme': 8,
          'GB': 8,
          'nice': 7,
          'noise': 7,
          '1': 7,
          'day': 7,
          'mic': 7,
          'around': 7,
          'app': 7,
          'light': 7,
          'charger': 7,
          'premium': 7,
          'feel': 7,
          'weight': 7,
          'But': 7,
          'want': 7,
          'much': 7,
          'gaming': 7,
          'doesnt': 7,
          '4G': 7,
          '2': 7,
          'storage': 7,
          'Phone': 7,
          'speaker': 7,
          'ek': 7,
          'kaafi': 7,
          'got': 6,
          'Best': 6,
          'purchased': 6,
          'Android': 6,
          'However': 6,
          'charge': 6,
          'recommend': 6,
          'better': 6,
          'apps': 6,
          'call': 6,
          'lot': 6,
          'side': 6,
          'purchase': 6,
          'variant': 6,
          'get': 6,
          'issues': 6,
          'daily': 6,
          'dont': 6,
          'fast': 6,
          'applications': 6,
          'support': 6,
          'feels': 6,
          'though': 6,
          'If': 6,
          'top': 6,
          'ke': 6,
          'jo': 6,
          'bhi': 6,
          'easy': 5,
          'need': 5,
          'look': 5,
          'strong': 5,
          'almost': 5,
          'magnet': 5,
          'tried': 5,
          'audio': 5,
          'still': 5,
          'okay': 5,
          'used': 5,
          'could': 5,
          '6': 5,
          'quite': 5,
          'super': 5,
          'since': 5,
          'giving': 5,
          'old': 5,
          'build': 5,
          'basic': 5,
          'processor': 5,
          'updates': 5,
          'service': 5,
          'notch': 5,
          'heavy': 5,
          'card': 5,
          'amazing': 5,
          'Great': 4,
          'Quality': 4,
          'definitely': 4,
          'perfect': 4,
          'handle': 4,
          'compatible': 4,
          'Highly': 4,
          'recommended': 4,
          'Value': 4,
          'option': 4,
          'mics': 4,
          'comes': 4,
          'first': 4,
          'Im': 4,
          'noice': 4,
          'microphone': 4,
          'return': 4,
          'last': 4,
          '4': 4,
          'work': 4,
          'You': 4,
          'review': 4,
          'WhatsApp': 4,
          'media': 4,
          'head': 4,
          'A': 4,
          'natural': 4,
          'gain': 4,
          'high': 4,
          'case': 4,
          'average': 4,
          'large': 4,
          'come': 4,
          'videos': 4,
          'anyone': 4,
          'looking': 4,
          'USBC': 4,
          'fantastic': 4,
          'wise': 4,
          'No': 4,
          'phoneRead': 4,
          'connection': 4,
          'cant': 4,
          'future': 4,
          'reliable': 4,
          'less': 4,
          'poor': 4,
          'Overall': 4,
          'run': 4,
          'least': 4,
          'centre': 4,
          'software': 4,
          'hardware': 4,
          'memory': 4,
          'nothing': 4,
          '5g': 4,
          'simultaneously': 4,
          'lag': 4,
          '5': 4,
          'bright': 4,
          'photos': 4,
          'dual': 4,
          '128': 4,
          'heating': 4,
          'front': 4,
          'brand': 4,
          'design': 4,
          'compared': 4,
          'M17': 4,
          'yeh': 4,
          'ki': 4,
          'hain': 4,
          'mount': 3,
          'moneyRead': 3,
          'outdoor': 3,
          'meetings': 3,
          'always': 3,
          'clip': 3,
          'small': 3,
          'already': 3,
          'happy': 3,
          'found': 3,
          'change': 3,
          'settings': 3,
          'default': 3,
          'especially': 3,
          'android': 3,
          'play': 3,
          'came': 3,
          'amazon': 3,
          'find': 3,
          'machine': 3,
          'along': 3,
          'without': 3,
          'calls': 3,
          'taking': 3,
          'hrs': 3,
          'go': 3,
          'far': 3,
          'pretty': 3,
          'power': 3,
          'replacement': 3,
          'clear': 3,
          'recording': 3,
          'control': 3,
          'things': 3,
          'doesn’t': 3,
          'iPhone': 3,
          'make': 3,
          'itRead': 3,
          'AI': 3,
          'started': 3,
          'priceRead': 3,
          'Screen': 3,
          'speakers': 3,
          'loud': 3,
          'usable': 3,
          'level': 3,
          'expect': 3,
          'Internet': 3,
          'data': 3,
          'enough': 3,
          'takes': 3,
          'pictures': 3,
          'didnt': 3,
          'ok': 3,
          'months': 3,
          'trust': 3,
          'available': 3,
          'mAh': 3,
          'Display': 3,
          'touch': 3,
          'tasks': 3,
          '4GB': 3,
          'slow': 3,
          'impressive': 3,
          'lags': 3,
          'gets': 3,
          'cannot': 3,
          'smoothly': 3,
          'products': 3,
          'extremely': 3,
          'durable': 3,
          'paid': 3,
          'point': 3,
          'company': 3,
          'disappointed': 3,
          'buying': 3,
          'new': 3,
          'budgetRead': 3,
          'given': 3,
          'version': 3,
          'test': 3,
          'theres': 3,
          'every': 3,
          'might': 3,
          'photo': 3,
          'space': 3,
          'aspects': 3,
          'durability': 3,
          'thanks': 3,
          'Nice': 3,
          'Bought': 3,
          'Pro': 3,
          'Also': 3,
          'So': 3,
          'modern': 3,
          'curved': 3,
          'else': 3,
          'redmi': 3,
          'previous': 3,
          'heat': 3,
          'user': 3,
          'single': 3,
          'segment': 3,
          'UI': 3,
          'stylish': 3,
          'In': 3,
          '15': 3,
          'exchange': 3,
          'different': 3,
          'P4x': 3,
          'deta': 3,
          'liye': 3,
          'ho': 3,
          '90': 3,
          'Mi': 2,
          '55': 2,
          'try': 2,
          'shoots': 2,
          'cameras': 2,
          'till': 2,
          'classy': 2,
          'content': 2,
          'people': 2,
          'big': 2,
          'And': 2,
          'difficult': 2,
          'Cant': 2,
          'record': 2,
          'class': 2,
          'qualityRead': 2,
          'useRead': 2,
          'Please': 2,
          'internal': 2,
          'instead': 2,
          'Later': 2,
          'setting': 2,
          'connect': 2,
          'worked': 2,
          'put': 2,
          'washing': 2,
          'another': 2,
          'meeting': 2,
          'however': 2,
          'allows': 2,
          'usually': 2,
          'forget': 2,
          'shirt': 2,
          '45': 2,
          '300': 2,
          'switch': 2,
          'anything': 2,
          'productRead': 2,
          'item': 2,
          'suggest': 2,
          'anywhere': 2,
          'received': 2,
          'fully': 2,
          'seconds': 2,
          'youRead': 2,
          'receive': 2,
          'included': 2,
          'receiver': 2,
          'done': 2,
          'clearRead': 2,
          'cancelation': 2,
          'satisfied': 2,
          'purchaseRead': 2,
          'Must': 2,
          'background': 2,
          'keeping': 2,
          'interviews': 2,
          'close': 2,
          'online': 2,
          'Mic': 2,
          'secure': 2,
          'must': 2,
          'crisp': 2,
          'cuts': 2,
          'week': 2,
          'comfortable': 2,
          'lasting': 2,
          'cost': 2,
          'regular': 2,
          '17': 2,
          'special': 2,
          'sure': 2,
          'save': 2,
          'devices': 2,
          'availableRead': 2,
          'students': 2,
          'worth': 2,
          'entry': 2,
          '16': 2,
          '8': 2,
          'affordable': 2,
          'For': 2,
          'including': 2,
          'etc': 2,
          'slight': 2,
          'WiFi': 2,
          'person': 2,
          'looks': 2,
          'connectivity': 2,
          '3': 2,
          'Support': 2,
          'provides': 2,
          'Performance': 2,
          'speed': 2,
          'Although': 2,
          'Software': 2,
          'suitable': 2,
          'expectations': 2,
          'compromisesRead': 2,
          'heated': 2,
          'moderate': 2,
          'highly': 2,
          'something': 2,
          'ordered': 2,
          'cellphone': 2,
          'tremendous': 2,
          'confidence': 2,
          'When': 2,
          'next': 2,
          'After': 2,
          'guys': 2,
          'everything': 2,
          'kind': 2,
          'behaving': 2,
          'drain': 2,
          'Even': 2,
          'exchanged': 2,
          'buyers': 2,
          'nicely': 2,
          'hangs': 2,
          '60': 2,
          'slot': 2,
          'hence': 2,
          'GHz': 2,
          'surprisingly': 2,
          'signal': 2,
          'SIM': 2,
          'room': 2,
          'take': 2,
          'makes': 2,
          'Click': 2,
          'noticeable': 2,
          'rate': 2,
          'On': 2,
          'solid': 2,
          'expected': 2,
          'know': 2,
          'lower': 2,
          'playing': 2,
          'never': 2,
          'felt': 2,
          'sleek': 2,
          'sunlight': 2,
          'photography': 2,
          'reading': 2,
          'stereo': 2,
          'actually': 2,
          'terms': 2,
          'face': 2,
          'capacity': 2,
          '6000': 2,
          '15x': 2,
          '7000': 2,
          'Worth': 2,
          'penny': 2,
          'lightweight': 2,
          'important': 2,
          'note': 2,
          '14': 2,
          'irritated': 2,
          'bgmi': 2,
          'fps': 2,
          'awesome': 2,
          'everyone': 2,
          'scratches': 2,
          'My': 2,
          'end': 2,
          'Amazing': 2,
          'delivery': 2,
          'Amazon': 2,
          'according': 2,
          'Really': 2,
          'colour': 2,
          'family': 2,
          'research': 2,
          '7': 2,
          '120': 2,
          'monster': 2,
          'factor': 2,
          'slim': 2,
          'Chinese': 2,
          'sacrifice': 2,
          'gamer': 2,
          'os': 2,
          'cover': 2,
          '—': 2,
          'OIS': 2,
          'colors': 2,
          'vibrant': 2,
          'Using': 2,
          'enjoyable': 2,
          'major': 2,
          'extra': 2,
          '16k': 2,
          'SIMs': 2,
          'totally': 2,
          'M32': 2,
          'brands': 2,
          'quickly': 2,
          'Daylight': 2,
          'choice': 2,
          'sometimes': 2,
          'goodRead': 2,
          'handset': 2,
          'karta': 2,
          'baat': 2,
          'ka': 2,
          'par': 2,
          'users': 2,
          'wajah': 2,
          'se': 2,
          'karna': 2,
          'jata': 2,
          'kar': 2,
          'leta': 2,
          'balanced': 2,
          'karne': 2,
          '15k': 2,
          'tv': 1,
          'inch': 1,
          '55K': 1,
          'wall': 1,
          'Price': 1,
          '30K': 1,
          'Tv': 1,
          'waste': 1,
          'beginners': 1,
          'Moto': 1,
          'loggingThe': 1,
          'Voice': 1,
          'qualities': 1,
          'comparability': 1,
          'It’s': 1,
          'science': 1,
          'functionality': 1,
          'simpleRead': 1,
          'Microphone': 1,
          'date': 1,
          'feature': 1,
          'iOS': 1,
          'creators': 1,
          'virtual': 1,
          'MoneyRead': 1,
          'Pros': 1,
          'Audio': 1,
          'beginnersCons': 1,
          'shortcoming': 1,
          'missing': 1,
          'magnets': 1,
          'lose': 1,
          'lost': 1,
          'losing': 1,
          'becomes': 1,
          'micRead': 1,
          'Bad': 1,
          'hollyland': 1,
          'Noise': 1,
          'properly': 1,
          'audioRead': 1,
          '1st': 1,
          'sorry': 1,
          '😁Read': 1,
          'read': 1,
          'doubts': 1,
          'respect': 1,
          'cancellationWhen': 1,
          'later': 1,
          'noticed': 1,
          'complained': 1,
          'scheduled': 1,
          'attempt': 1,
          'googling': 1,
          'gemini': 1,
          'ai': 1,
          'picking': 1,
          'cancelled': 1,
          'kept': 1,
          'There': 1,
          'external': 1,
          'able': 1,
          'micHollyland': 1,
          'please': 1,
          'send': 1,
          'instruction': 1,
          'manual': 1,
          'micIt': 1,
          'Easy': 1,
          'reels': 1,
          'edits': 1,
          'thereRead': 1,
          'specially': 1,
          'write': 1,
          'Why': 1,
          'By': 1,
          'mistake': 1,
          'shirts': 1,
          'recalled': 1,
          'start': 1,
          'clicked': 1,
          'inside': 1,
          'ran': 1,
          'stopped': 1,
          '1015': 1,
          'mins': 1,
          'wetconclusion': 1,
          'thought': 1,
          'wet': 1,
          'claimed': 1,
          'IP': 1,
          'rating': 1,
          'coincidentVery': 1,
          'sitting': 1,
          'direction': 1,
          'coolers': 1,
          'throwI': 1,
          'teams': 1,
          'windows': 1,
          'superb': 1,
          'wellCaution': 1,
          'Finding': 1,
          'core': 1,
          'purpose': 1,
          'supported': 1,
          'select': 1,
          'inputs': 1,
          'PC': 1,
          'breeze': 1,
          'observed': 1,
          'operational': 1,
          'continuous': 1,
          '1040': 1,
          'oneIts': 1,
          'hardly': 1,
          'notice': 1,
          'stuck': 1,
          '11000': 1,
          'bettee': 1,
          'dailyRead': 1,
          'output': 1,
          'feom': 1,
          'packed': 1,
          'damage': 1,
          'Noice': 1,
          'reduction': 1,
          'Better': 1,
          'customisationRead': 1,
          'loadedHello': 1,
          'workingBoth': 1,
          'transmitters': 1,
          'turning': 1,
          'pressing': 1,
          'button': 1,
          'several': 1,
          'responseI': 1,
          'allowing': 1,
          'proceedIt': 1,
          'seems': 1,
          'defective': 1,
          'replacementPlease': 1,
          'arrange': 1,
          'soon': 1,
          'possible': 1,
          'Thank': 1,
          'Charge': 1,
          'olug': 1,
          'usbc': 1,
          'grab': 1,
          'boom': 1,
          'connected': 1,
          'press': 1,
          'botton': 1,
          'carry': 1,
          'YouTuber': 1,
          'Iphone': 1,
          '17pro': 1,
          'max': 1,
          'it’s': 1,
          'buy✌🏻Read': 1,
          'ProsExcellent': 1,
          'Filters': 1,
          'effectively': 1,
          'subject’s': 1,
          'focusedHighquality': 1,
          'Clear': 1,
          'sound—good': 1,
          'vlogging': 1,
          'recordingsStrong': 1,
          'set': 1,
          'subject': 1,
          'isn’t': 1,
          'micVersatile': 1,
          'cases': 1,
          'Suitable': 1,
          'voiceovers': 1,
          'podcasts': 1,
          'classes': 1,
          'vlogs': 1,
          'etcConvenient': 1,
          'Having': 1,
          'helpful': 1,
          'sessions': 1,
          'usesConsAppdependent': 1,
          'adjusted': 1,
          'limits': 1,
          'cameraBattery': 1,
          'longer': 1,
          'require': 1,
          'frequent': 1,
          'chargingRange': 1,
          'limitations': 1,
          'wireless': 1,
          'typical': 1,
          'ideal': 1,
          'venues': 1,
          'obstructed': 1,
          'environmentsMagnet': 1,
          'transmitter': 1,
          'uses': 1,
          'rather': 1,
          'traditional': 1,
          'clothing': 1,
          'typesRead': 1,
          'loadedWorth': 1,
          'download': 1,
          'heck': 1,
          'attach': 1,
          'clothes': 1,
          'bulkyPS': 1,
          'receivers': 1,
          'lighting': 1,
          'singular': 1,
          'usbRead': 1,
          'loadedVery': 1,
          'genuine': 1,
          'writing': 1,
          'charged': 1,
          'based': 1,
          'vary': 1,
          'Over': 1,
          'little': 1,
          'higher': 1,
          'endRead': 1,
          'Brilliant': 1,
          'creation': 1,
          'Works': 1,
          'charm': 1,
          'Of': 1,
          'mention': 1,
          'brilliant': 1,
          'ambient': 1,
          'beautifully': 1,
          'ONLY': 1,
          'combo': 1,
          'Lightning': 1,
          'upwards': 1,
          'Rs7000': 1,
          'kit': 1,
          'wasnt': 1,
          'bloggingI’m': 1,
          'industry': 1,
          'Loved': 1,
          'Have': 1,
          'Clips': 1,
          'Will': 1,
          'Lose': 1,
          'ItRead': 1,
          'Lark': 1,
          'Both': 1,
          'transmittors': 1,
          'What': 1,
          'nextRead': 1,
          'crystal': 1,
          'nowYou': 1,
          'parents': 1,
          'useTotally': 1,
          'According': 1,
          'batterylight': 1,
          'grandparents': 1,
          'learn': 1,
          'smartphoneRead': 1,
          '67': 1,
          'Large': 1,
          'ui': 1,
          'Don’t': 1,
          'Prices': 1,
          'Gifting': 1,
          'someone': 1,
          'satisfactory': 1,
          'Attractive': 1,
          'Product': 1,
          'PricesRead': 1,
          'marketed': 1,
          'Nonetheless': 1,
          'midrange': 1,
          'essentials': 1,
          'browsing': 1,
          'dropped': 1,
          'wifi': 1,
          'despite': 1,
          'proximity': 1,
          'router': 1,
          'Itll': 1,
          'consume': 1,
          'realise': 1,
          'avoid': 1,
          'rapid': 1,
          'switching': 1,
          'dataRead': 1,
          'gift': 1,
          'likes': 1,
          'although': 1,
          'FHD': 1,
          'panel': 1,
          'colourful': 1,
          'general': 1,
          'youtube': 1,
          'Speaker': 1,
          'via': 1,
          'She': 1,
          'game': 1,
          'comment': 1,
          'check': 1,
          'shes': 1,
          'home': 1,

In [48]:
vocabulary_title = {
    word: idx 
    for idx, (word, freq) 
    in enumerate(Title_words.most_common())
}

In [49]:
vocabulary_review = {
    word: idx 
    for idx, (word, freq) 
    in enumerate(Reviews_word.most_common())
}

In [57]:
print("\nTop 20 most frequent words:")
print("-" * 30)
for word, freq in Title_words.most_common(20):
    print(f"  {word:<20} : {freq} times")

Top 20 most frequent words:
------------------------------
  phone                : 20 times
  Good                 : 19 times
  good                 : 15 times
  product              : 12 times
  Best                 : 9 times
  money                : 8 times
  Great                : 6 times
  Very                 : 5 times
  buy                  : 5 times
  price                : 5 times
  range                : 5 times
  quality              : 5 times
  Value                : 4 times
  Nice                 : 4 times
  Awesome              : 4 times
  Phone                : 4 times
  Samsung              : 4 times
  5G                   : 4 times
  battery              : 4 times
  mobile               : 4 times

In [77]:
df

,Review Title,Review Description
0,Very very high cost.,"I got Mi tv 55 inch at 55K price, the wall mou..."
1,"Great product, you should buy for it if you ar...","Great product for beginners, you should try it..."
2,It is THE MIC that you need for everyday conte...,Best Microphone that I have purchased till dat...
3,Good mic but Bad magnet,Pros - It is a great product in this price ran...
4,Quality is not good,Very Bad Quality product from hollyland. Noise...
...,...,...
95,Good phone you can buy,In this price phone is very good but device is...
96,Worst Phone,Battery drain issue. They claim 7000+ mah but ...
97,Good phone,Good phone and camera quality is good.Read more
98,Redmi A5 is an excellent mobile phone.,This mobile is as per my expectations. It is e...
99,Awesome Product.,Awesome Product.Read more

In [100]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

enocoded_title = encoder.fit_transform(df)
enocoded_title

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 400 stored elements and shape (100, 390)>

In [105]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
ohe_matrix = mlb.fit_transform(df["cleaned_Title"])

print("OHE Matrix Shape:", ohe_matrix.shape)
print("\nVocabulary sample:", mlb.classes_[:10])
print("\nFirst title:", df["cleaned_Title"][0])
print("OHE Vector  :\n", ohe_matrix[0])

OHE Matrix Shape: (100, 62)

Vocabulary sample: [' ' '0' '1' '2' '3' '4' '5' '6' '7' '8']

First title: Very high cost
OHE Vector  :
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1
 0 1 0 1 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0]

In [94]:
from sklearn.feature_extraction.text import CountVectorizer

bow_vectorizer = CountVectorizer()


bow_matrix = bow_vectorizer.fit_transform(
   df["cleaned_Title"]
)

print("BoW Matrix Shape:", bow_matrix.shape)
print(list(bow_vectorizer.vocabulary_.items())[:10])
print("BoW Vector:\n", bow_matrix[0].toarray()[0])
print("Vocabulary size :", len(bow_vectorizer.vocabulary_))
print("\nSample vocabulary:")
print("\nFirst title:", df["cleaned_Title"][0])

BoW Matrix Shape: (100, 167)
[('very', 155), ('high', 66), ('cost', 38), ('great', 60), ('product', 118), ('buy', 30), ('beginner', 21), ('it', 73), ('the', 145), ('mic', 88)]
BoW Vector:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
Vocabulary size : 167

Sample vocabulary:

First title: Very high cost

In [101]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(df["cleaned_Title"])

print("TF-IDF Matrix Shape:", tfidf_matrix.shape)
print("Vocabulary sample:", list(tfidf_vectorizer.vocabulary_.items())[:10])
print("TF-IDF Vector for first title:\n", tfidf_matrix[0].toarray())

TF-IDF Matrix Shape: (100, 167)
Vocabulary sample: [('very', 155), ('high', 66), ('cost', 38), ('great', 60), ('product', 118), ('buy', 30), ('beginner', 21), ('it', 73), ('the', 145), ('mic', 88)]
TF-IDF Vector for first title:
 [[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.61976745 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.61976745 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.48143185
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]]

In [106]:
# Shape analysis
print("OHE Matrix Shape:", ohe_matrix.shape)
print("BoW Matrix Shape:", bow_matrix.shape)
print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

# Sparsity calculation
def calculate_sparsity(matrix):
    total_elements = matrix.shape[0] * matrix.shape[1]
    non_zero_elements = matrix.nnz
    sparsity = non_zero_elements / total_elements
    return sparsity

print("\nSparsity:")
# Shape analysis
print("OHE Matrix Shape:", ohe_matrix.shape)
print("BoW Matrix Shape:", bow_matrix.shape)
print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

# Sparsity calculation
def calculate_sparsity(matrix):
    total_elements = matrix.shape[0] * matrix.shape[1]
    if hasattr(matrix, 'nnz'):  # For sparse matrices
        non_zero_elements = matrix.nnz
    else:  # For dense arrays
        non_zero_elements = np.count_nonzero(matrix)
    sparsity = non_zero_elements / total_elements
    return sparsity

print("\nSparsity:")
print("OHE Matrix Sparsity:", calculate_sparsity(ohe_matrix))
print("BoW Matrix Sparsity:", calculate_sparsity(bow_matrix))
print("TF-IDF Matrix Sparsity:", calculate_sparsity(tfidf_matrix))

OHE Matrix Shape: (100, 62)
BoW Matrix Shape: (100, 167)
TF-IDF Matrix Shape: (100, 167)

Sparsity:
OHE Matrix Shape: (100, 62)
BoW Matrix Shape: (100, 167)
TF-IDF Matrix Shape: (100, 167)

Sparsity:
OHE Matrix Sparsity: 0.21725806451612903
BoW Matrix Sparsity: 0.021137724550898202
TF-IDF Matrix Sparsity: 0.021137724550898202

In [ ]:

import numpy as np
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
# Use cleaned titles already created in notebook
titles = df['cleaned_Title'].fillna('').astype(str)
tokenized_titles = [t.split() for t in titles]

# 1) Proper word-level OHE
mlb_word = MultiLabelBinarizer()
ohe_word = mlb_word.fit_transform(tokenized_titles)

# 2) BoW and TF-IDF
bow_vec = CountVectorizer()
bow_mat = bow_vec.fit_transform(titles)

tfidf_vec = TfidfVectorizer()
tfidf_mat = tfidf_vec.fit_transform(titles)
# Helper: density and zero percentage
def matrix_stats(name, mat):
    total = mat.shape[0] * mat.shape[1]
    non_zero = np.count_nonzero(mat) if isinstance(mat, np.ndarray) else mat.nnz
    density = non_zero / total
    zero_pct = (1 - density) * 100
    return {
        'Method': name,
        'Shape': f'{mat.shape[0]} x {mat.shape[1]}',
        'NonZeroDensity': round(density, 6),
        'ZeroPercent': round(zero_pct, 2)
    }

comparison_df = pd.DataFrame([
    matrix_stats('OHE (Word-Level)', ohe_word),
    matrix_stats('BoW', bow_mat),
    matrix_stats('TF-IDF', tfidf_mat)
])
print('Task 4 + 5 Comparison Table:')
display(comparison_df)

# 3) TF-IDF importance: high-IDF words vs common words
idf_df = pd.DataFrame({
    'word': tfidf_vec.get_feature_names_out(),
    'idf': tfidf_vec.idf_
}).sort_values('idf', ascending=False)

print('Top 15 High-IDF (more unique/informative) words:')
display(idf_df.head(15))

freq_series = pd.Series(Title_words).sort_values(ascending=False)
common_words = set(freq_series.head(15).index)
common_idf = idf_df[idf_df['word'].isin(common_words)].sort_values('idf')
print('Common frequent words and their IDF (usually lower weight):')
display(common_idf.head(15))

# 4) Task 6 concise answers (kept in notebook output, no Task 7)
answers = {
    'Why BoW fails semantically': 'Ignores context, word order, and synonym relationships.',
    'When to use BoW': 'Simple baseline, small/controlled datasets, fast experiments.',
    'When to use TF-IDF': 'Need better discrimination by down-weighting very common words.',
    'TF-IDF limitations': 'No deep semantics/context, sensitive to noisy rare terms, order ignored.'
}
print('Task 6 Answers:')
for k, v in answers.items():
    print(f'- {k}: {v}')

Task 4 + 5 Comparison Table:

             Method      Shape  NonZeroDensity  ZeroPercent
0  OHE (Word-Level)  100 x 202        0.017921        98.21
1               BoW  100 x 167        0.021138        97.89
2            TF-IDF  100 x 167        0.021138        97.89

Top 15 High-IDF (more unique/informative) words:

          word       idf
0          15x  4.921973
1         2026  4.921973
3           4g  4.921973
6           a5  4.921973
5         8000  4.921973
8   affordable  4.921973
7   absolutely  4.921973
38        cost  4.921973
36  conference  4.921973
9        after  4.921973
10        also  4.921973
12      amoled  4.921973
13          an  4.921973
14     average  4.921973
15        away  4.921973

Common frequent words and their IDF (usually lower weight):

        word       idf
59      good  2.088760
112    phone  2.396245
118  product  2.976063
93     money  3.312535
121  quality  3.535679
115    price  3.823361
122    range  3.823361
30       buy  4.005683

Task 6 Answers:
- Why BoW fails semantically: Ignores context, word order, and synonym relationships.
- When to use BoW: Simple baseline, small/controlled datasets, fast experiments.
- When to use TF-IDF: Need better discrimination by down-weighting very common words.
- TF-IDF limitations: No deep semantics/context, sensitive to noisy rare terms, order ignored.